In [34]:
import sys
import os
from pprint import pprint
import gdcm
import pydicom as dicom
import pylab
import numpy as np

In [59]:
# for root, subdirs, files in os.walk(os.path.join(os.getenv('HOME'), 'FetalLung')):
dims = []
for root, subdirs, files in os.walk('/home/mazin/FetalLung/FetalLungAbnormal'):
#     print(root)
    if not files:
        continue
    for file in files:
        if not file.endswith('.dcm'):
            continue
#         print(file)
        dim, orient = dims_and_orient(os.path.join(root, file))
        dims.append(dim)     
npdims = np.array(dims)

In [53]:
dims
npdims = np.array(dims)

[[    64     59]
 [    66      5]
 [    86      7]
 [   128    211]
 [   256  10536]
 [   512 122646]]


In [60]:
npdims1 = npdims

In [58]:
unique, counts = np.unique(npdims[:,0], return_counts=True)
print np.asarray((unique, counts)).T

unique, counts = np.unique(npdims[:,1], return_counts=True)
print np.asarray((unique, counts)).T

sum(npdims[:,0] != npdims[:,1])

[[    64     59]
 [    66      5]
 [    86      7]
 [   128    211]
 [   256  10536]
 [   512 122646]]
[[    13      3]
 [    25      4]
 [    49      2]
 [    61      3]
 [    64     59]
 [   128    211]
 [   256  10536]
 [   512 122646]]


12

In [27]:
file = "/home/mazin/FetalLung/FetalLungAbnormal/patient/LC20151230256/AX SSFSExr BODY/IM-0921-0001-d.dcm"
file = "/home/mazin/FetalLung/FetalLungAbnormal/patient/LC2584563/SAG SSFSE BODY/IM-0602-0023-d.dcm"

def dims_and_orient(file):
    r = gdcm.ImageReader()
    r.SetFileName(file)
    if not r.Read():
      sys.exit(1)
    ir = r.GetImage()

    # dimensions
    dims = ir.GetDimensions()
#     print(ir.GetDimension(0))
#     print(ir.GetDimension(1))
#     print("Dims:",dims)

    # orientation
    dircos =  ir.GetDirectionCosines()
    t = gdcm.Orientation.GetType(tuple(dircos))
    l = gdcm.Orientation.GetLabel(t)
#     print("Orientation label:",l)
    
    return tuple(dims), l
    
dims_and_orient(file)

((512, 512), 'AXIAL')

In [28]:
file = "/home/mazin/FetalLung/FetalLungAbnormal/patient/LC20151230256/AX SSFSExr BODY/IM-0921-0001-d.dcm"
def view_dicom(file):
    ds = dicom.read_file(file)
    pix = ds.pixel_array

    pylab.imshow(ds.pixel_array, cmap=pylab.cm.bone)
    # pylab.imshow(ds.pixel_array)
    pylab.show()
    # plt.imsave('test.png', ds.pixel_array, cmap=pylab.cm.bone)
